version: '3.1'

services:

  web:
    build: .
    image: wordpress-secure
    container_name: wp_web
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
      - 8443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      # mount local directory inside container www root
      - ${local_web_dir}:/var/www/html

  db:
    image: library/mariadb:latest
    container_name: wp_db
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ${local_db_dir}:/var/lib/mysql

